In [91]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [106]:
import pandas as pd
from matplotlib import pyplot as plt
from pathlib import Path
import numpy as np
import sys
sys.path.append("../model/")
sys.path.append("../tools/")
from MLP_classifier import MultiClassClassifier
from dataset import TaskA
import torch

In [119]:
device = "cuda:0"
clf = MultiClassClassifier(n_classes=2).to(device)
clf.eval()

data = TaskA(load_from_disk=True,path="/data4/saland/data/taskA.pt")
data_csv = pd.read_csv("../../docs/scan.csv").iloc[:3333]

In [120]:
data_csv.head(15)

Unnamed: 0      image_name  class
0            0  A_005fbfn6.png      1
1            1  A_0060ug9j.png      1
2            2  A_00el4hwr.png      0
3            3  A_00h6ucsm.png      1
4            4  A_00hzao5p.png      0
5            5  A_00jghend.png      1
6            6  A_00kj5fih.png      1
7            7  A_00ww8c88.png      1
8            8  A_0102obzc.png      1
9            9  A_012n784o.png      0
10          10  A_014yzlf7.png      1
11          11  A_016d3o4o.png      1
12          12  A_01cays4r.png      1
13          13  A_01heykmf.png      1
14          14  A_01hr8c4e.png      1

In [128]:
pred_true = {name: {"predicted": None, "true": None} for name in data.image_name}
correctness = []
sorted_names = sorted(data.image_name)
for name in sorted_names[:3333]:
    true_label = data_csv[data_csv["image_name"] == name]["class"].item()
    with torch.no_grad():
        predicted_label = 1 - torch.argmax(clf(data.features[name].to(device))).item() # for the model 0 is fake and 1 real but this is reversed for scan.csv data
    correctness.append(1 if predicted_label == true_label else 0)
print("accuracy:",sum(correctness)/len(correctness))

tensor([[0.1008, 0.0760]], device='cuda:0')
1
tensor([[0.0139, 0.0708]], device='cuda:0')
0
tensor([[ 0.0784, -0.0657]], device='cuda:0')
1
tensor([[-0.1665, -0.0717]], device='cuda:0')
0
tensor([[0.0364, 0.0063]], device='cuda:0')
1
tensor([[0.3130, 0.1425]], device='cuda:0')
1
tensor([[ 0.0501, -0.0096]], device='cuda:0')
1
tensor([[-0.0682, -0.0070]], device='cuda:0')
0
tensor([[ 0.0470, -0.2324]], device='cuda:0')
1
tensor([[-0.0456, -0.1762]], device='cuda:0')
1
tensor([[-0.3130, -0.1161]], device='cuda:0')
0
tensor([[-0.0876,  0.0804]], device='cuda:0')
0
tensor([[0.0231, 0.0477]], device='cuda:0')
0
tensor([[-0.0683, -0.2935]], device='cuda:0')
1
tensor([[0.1356, 0.0311]], device='cuda:0')
1
tensor([[-0.1847,  0.0337]], device='cuda:0')
0
tensor([[0.0827, 0.0264]], device='cuda:0')
1
tensor([[0.0489, 0.0561]], device='cuda:0')
0
tensor([[ 0.1441, -0.0664]], device='cuda:0')
1
tensor([[-0.2071,  0.0447]], device='cuda:0')
0
tensor([[0.2228, 0.2132]], device='cuda:0')
1
tensor([[-

KeyboardInterrupt: 

In [86]:
train_names = sorted(data.image_name)[:100]
test_names  = sorted(data.image_name)[100:3333]
idx = list(enumerate(zip(data.image_name,data_csv.iloc[:100]["class"])))

idx = sorted(enumerate(data.image_name))
idx

[(0, 'A_3xbmlqqx.png'),
 (1, 'A_6uq7gptk.png'),
 (2, 'A_05r360ki.png'),
 (3, 'A_edzollj2.png'),
 (4, 'A_pehexxfk.png'),
 (5, 'A_dae01u4v.png'),
 (6, 'A_w71kp27y.png'),
 (7, 'A_nsfulnf1.png'),
 (8, 'A_yn2aw8dy.png'),
 (9, 'A_296img8w.png'),
 (10, 'A_1pa72d74.png'),
 (11, 'A_u7ulapm2.png'),
 (12, 'A_hjb6ho1i.png'),
 (13, 'A_sicrjz2n.png'),
 (14, 'A_b49lb847.png'),
 (15, 'A_x16viz4s.png'),
 (16, 'A_1yvsugw7.png'),
 (17, 'A_32krdsat.png'),
 (18, 'A_k2nv16cp.png'),
 (19, 'A_b2s8ck39.png'),
 (20, 'A_aogofb3v.png'),
 (21, 'A_upod7eva.png'),
 (22, 'A_obluvp6p.png'),
 (23, 'A_v9242cwi.png'),
 (24, 'A_jqe8k1e9.png'),
 (25, 'A_46qpqqso.png'),
 (26, 'A_2lfozv1c.png'),
 (27, 'A_qrp8gzdx.png'),
 (28, 'A_ha3mybxs.png'),
 (29, 'A_c6qh57xn.png'),
 (30, 'A_ctxv1yjg.png'),
 (31, 'A_0cj49psx.png'),
 (32, 'A_hph3c5hv.png'),
 (33, 'A_2ihe9b33.png'),
 (34, 'A_io7yvwif.png'),
 (35, 'A_z6pngjtr.png'),
 (36, 'A_zhgb8yxh.png'),
 (37, 'A_z7549ki8.png'),
 (38, 'A_uyq3o2oy.png'),
 (39, 'A_8p2l42y5.png'),
 (40, 'A_c